Map<String, String> req = {
  "accountNumber": "Account Number",
  "reqAccountHolderName": "Required Account Holder Name",
  "date": "Date",
  "date": "Date",
  "date": "Date",

  "reqYourFullName": "Required Your full name",
  "reqYourMobileNumber": "Required Your Mobile Number",
  "reqEmail": "Required Email",
  "reqDateBirth": "Required Date of Birth ",
  "reqDateMarriage": "Required Date of Marriage",
  "reqAddressLine": "Required Address Line 1 ",
  "reqCountry": "Required Country",
  "reqState": "Required State",
  "reqCity": "Required City",
  "reqPinCode": "Required Pin Code",
  "reqBankA/CNo.": "Required Bank A/C No.",
  "reqBankName": "Required Bank Name",
  "reqBranchName": "Required Branch Name",
  "reqIFSC": "Required IFSC Code",
  "reqPan": "Required Pan No.",
  "reqUpi": "Required Enter Your UPI ID",
};
