// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmIhE8rmluuiq19Ie7N5Oaiamzfw94Igg',
    appId: '1:195877756947:web:3860914e9c27a46d30dfe6',
    messagingSenderId: '195877756947',
    projectId: 'fir-series-8ee80',
    authDomain: 'fir-series-8ee80.firebaseapp.com',
    storageBucket: 'fir-series-8ee80.firebasestorage.app',
    measurementId: 'G-H6CS23QNWM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYCT9p9Aw1pZNz2R44WnybMuZqec44kAs',
    appId: '1:195877756947:android:4693ae25343d7d8e30dfe6',
    messagingSenderId: '195877756947',
    projectId: 'fir-series-8ee80',
    storageBucket: 'fir-series-8ee80.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAs9poz2vCGNRa-mA0p_Ff3KLX3QjpNUss',
    appId: '1:195877756947:ios:0a8b47f33e5414ef30dfe6',
    messagingSenderId: '195877756947',
    projectId: 'fir-series-8ee80',
    storageBucket: 'fir-series-8ee80.firebasestorage.app',
    iosBundleId: 'com.example.myProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAs9poz2vCGNRa-mA0p_Ff3KLX3QjpNUss',
    appId: '1:195877756947:ios:0a8b47f33e5414ef30dfe6',
    messagingSenderId: '195877756947',
    projectId: 'fir-series-8ee80',
    storageBucket: 'fir-series-8ee80.firebasestorage.app',
    iosBundleId: 'com.example.myProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmIhE8rmluuiq19Ie7N5Oaiamzfw94Igg',
    appId: '1:195877756947:web:f33e92d0786fe31a30dfe6',
    messagingSenderId: '195877756947',
    projectId: 'fir-series-8ee80',
    authDomain: 'fir-series-8ee80.firebaseapp.com',
    storageBucket: 'fir-series-8ee80.firebasestorage.app',
    measurementId: 'G-MH8CDQ2E2V',
  );
}
